### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by UsernameNotActive** [YUNG-GANG/YUNGs-Better-Strongholds#13]
When I go near a chunk that has a stronghold the games crashes and I get a IllegalStateException: Missing registry error.

Full crash log:
java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / minecraft:worldgen/structure_feature]
	at net.minecraft.util.registry.DynamicRegistries.lambda$registryOrThrow$4(DynamicRegistries.java:61) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.DynamicRegistries$$Lambda$9008/1340832443.get(Unknown Source) ~[?:?] {}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51] {}
	at net.minecraft.util.registry.DynamicRegistries.func_243612_b(DynamicRegistries.java:60) ~[?:?] {re:classloading,re:mixin}
	at fudge.notenoughcrashes.mixinhandlers.MixinHandler.placeBlameOnBrokenStructures(MixinHandler.java:18) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.biome.Biome.handler$zzj000$addStructureDetails(Biome.java:1067) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:MixinBiome,pl:mixin:APP:notenoughcrashes.forge.mixins.json:MixinBiomeStructureDetails,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinBiomeClient,pl:mixin:A}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:237) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:MixinBiome,pl:mixin:APP:notenoughcrashes.forge.mixins.json:MixinBiomeStructureDetails,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinBiomeClient,pl:mixin:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:betterstrongholds.mixins.json:VanillaStrongholdSpawnMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2334/1531675854.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$10637/1111060997.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$10634/1187826954.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$10526/1444035304.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by TelepathicGrunt** [comment]
@UsernameNotActive can you remove notenoughcrashes and performant first? Then put on [Blame mod](https://www.curseforge.com/minecraft/mc-mods/blame/files/3181314) and get the crash again. Then show us the latest.log file from the config folder instead of the crashlog file. This will tell us all the information we need

**Comment by yungnickyoung** [comment]
Closing due to inactivity.
