### ISSUE TITLE
Ender_eye can't throw

### ISSUE THREAD

**Issue by chemhell** [YUNG-GANG/YUNGs-Better-Strongholds#25]
Now I'm using Mohist server. When I throw the eye,it just do nothing. When use /locate betterstrongholds it wrongs, and my server says: 
`[00:30:44 WARN]: java.lang.NullPointerException
[00:30:44 WARN]:        at net.minecraft.world.gen.ChunkGenerator.func_235956_a_(ChunkGenerator.java:177)
[00:30:44 WARN]:        at com.telepathicgrunt.repurposedstructures.utils.StructureLocator.returnClosestStronghold(StructureLocator.java:19)
[00:30:44 WARN]:        at net.minecraft.item.EnderEyeItem.localvar$zzb000$repurposedstructures_locateRSStrongholds(EnderEyeItem.java:521)
[00:30:44 WARN]:        at net.minecraft.item.EnderEyeItem.func_77659_a(EnderEyeItem.java:92)
[00:30:44 WARN]:        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:247)
[00:30:44 WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:352)
[00:30:44 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:1486)
[00:30:44 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:30)
[00:30:44 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:9)
[00:30:44 WARN]:        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:868)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:178)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:851)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:845)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:831)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:763)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271)
[00:30:44 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by chemhell** [comment]
[00:30:44 WARN]: java.lang.NullPointerException
[00:30:44 WARN]:        at net.minecraft.world.gen.ChunkGenerator.func_235956_a_(ChunkGenerator.java:177)
[00:30:44 WARN]:        at com.telepathicgrunt.repurposedstructures.utils.StructureLocator.returnClosestStronghold(StructureLocator.java:19)
[00:30:44 WARN]:        at net.minecraft.item.EnderEyeItem.localvar$zzb000$repurposedstructures_locateRSStrongholds(EnderEyeItem.java:521)
[00:30:44 WARN]:        at net.minecraft.item.EnderEyeItem.func_77659_a(EnderEyeItem.java:92)
[00:30:44 WARN]:        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:247)
[00:30:44 WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:352)
[00:30:44 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:1486)
[00:30:44 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:30)
[00:30:44 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:9)
[00:30:44 WARN]:        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:868)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:178)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:851)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:845)
[00:30:44 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:831)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:763)
[00:30:44 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271)
[00:30:44 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by yungnickyoung** [comment]
Make sure you have the latest version of both Better Strongholds and Repurposed Structures

**Comment by chemhell** [comment]
> Make sure you have the latest version of both Better Strongholds and Repurposed Structures

yes my server use Repurposed Structures 2.7.5 and BetterStrongholds-1.16.4-1.1, it's latest version.
Single player game do not have this problem, '/locate betterstrongholds' and Ender_eye works

**Comment by yungnickyoung** [comment]
Can you pastebin the full crashlog and latest.log?

**Comment by TelepathicGrunt** [comment]
@chemhell This should've been on my repurposed structures github lol. But anyway, looking at the code on just forge, I dont see how this crash is at all possible unless mohist changed the Chunkgenerator.findNearestMapFeature method and removed the null check or something. I think this is a Mohist issue as they are known for missing lots of forge implementations and doing invasive changes that breaks mods. If you take your modpack and put it on a Forge only world locally, does the locate command and eye work? If so, then yeah, it's a Mohist issue that's outside my control

**Comment by chemhell** [comment]
> 你能粘贴完整的崩溃日志和最新的.log吗？

Server did not crash, i just can't use the ender_eye.

**Comment by chemhell** [comment]
> @chemhell This should've been on my repurposed structures github lol. But anyway, looking at the code on just forge, I dont see how this crash is at all possible unless mohist changed the Chunkgenerator.findNearestMapFeature method and removed the null check or something. I think this is a Mohist issue as they are known for missing lots of forge implementations and doing invasive changes that breaks mods. If you take your modpack and put it on a Forge only world locally, does the locate command and eye work? If so, then yeah, it's a Mohist issue that's outside my control

oh, maybe, I'll cheke in forgeserver

**Comment by yungnickyoung** [comment]
Yeah, this is a problem with Mohist. Unfortunately we can't really help you there. I recommend not using Mohist if at all possible. They are notorious for making breaking changes that can cause a lot of problems.
