### ISSUE TITLE
Minecraft 1.19.2 (Fabric) won't launch with YUNGs-Better-Strongholds in the mod folder.

### ISSUE THREAD

**Issue by MossSoda** [YUNG-GANG/YUNGs-Better-Strongholds#76]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterstrongholds'!

Error Code: -1

Heres the Crash report:
---------------------------------------------------------------------------------------------------------------------------------------------------
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterstrongholds'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                                                                                                                  
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
	at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:73)
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92)
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
	at com.yungnickyoung.minecraft.betterstrongholds.module.ConfigModuleFabric.init(ConfigModuleFabric.java:28)
	at com.yungnickyoung.minecraft.betterstrongholds.services.FabricModulesLoader.loadModules(FabricModulesLoader.java:9)
	at com.yungnickyoung.minecraft.betterstrongholds.BetterStrongholdsCommon.init(BetterStrongholdsCommon.java:16)
	at com.yungnickyoung.minecraft.betterstrongholds.BetterStrongholdsFabric.onInitialize(BetterStrongholdsFabric.java:8)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                                                                                                                  
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
---------------------------------------------------------------------------------------------------------------------------------------------------

I've tried updating the YUNGs API, and the fabric API.

**Comment by yungnickyoung** [comment]
Sorry for being so late on this, but it looks like your config corrupted for some reason. If you delete the old config files and re-start the game, you should be good to go.
